name: scmil
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  - scanpy
  - anndata
  - h5py
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - statsmodels
  - umap-learn
  - matplotlib
  - seaborn
  - pyyaml
  - pytorch

  - scikit-misc=0.5.2
