[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scmil"
version = "0.1.0"
description = "scRNA-seq MIL pipeline"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
